version: '3.8'

services:
  gateway:
    build:
      context: mock-gateway
      dockerfile: ./Dockerfile
    image: gateway
    ports:
    - '8090:8090'
    networks:
    - docker_network
    healthcheck:
      test: java --version || exit 1
      interval: 10s
      retries: 10
      start_period: 5s
      timeout: 60s

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
    - '27017:27017'
    volumes:
    - mongodb_vol:/data/db
    networks:
    - docker_network

  abdm-wrapper:
    build: .
    image: abdm-wrapper
    ports:
    - '8082:8082'
    depends_on:
      gateway:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
    - docker_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb_vol:

networks:
  docker_network:
    driver: bridge
