version: '3.8'
services:
  fhir-mapper:
    build:
      dockerfile: Dockerfile
    image: fhir-mapper
    ports:
      - '8085:8085'
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge